service: cart-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  optimize:
    external: ['swagger-ui-dist']